PROG=cksum
SRCS=cksum.c crc.c md2.c md4.c md5.c print.c rmd160.c sha1.c sha256.c sha384.c sha512.c sum1.c sum2.c

LDADD += -lmd
SYMLINKS = sum md2 md4 md5 sha1 sha256 sha384 sha512 rmd160

.include "../../mk/prog.mk"
