LIB=netbsd
SRCS=fgetln.c reallocarr.c strsuftoll.c progname.c vwarnc.c warnc.c errc.c vsnprintf_ss.c \
	strmode.c snprintf_ss.c setmode.c vwarn.c vis.c devname.c chflags.c strtoi.c \
	humanize_number.c fgetwln.c verrc.c utimens.c strtou.c fparseln.c strtonum.c \
	arc4random.c

CPPFLAGS += -Iinclude/
CPPFLAGS += 

.include "../../mk/lib.mk"
