PROG=diff
SRCS=diff.c diffdir.c diffreg.c xmalloc.c

CPPFLAGS += -Wno-unused-value
CPPFLAGS += -Wno-pointer-sign
CPPFLAGS += -Wno-format
CPPFLAGS += -Wno-pointer-integer-compare

.include "../../mk/prog.mk"
