PROG=awk
SRCS=awkgram.tab.c lex.c b.c main.c parse.c proctab.c tran.c lib.c run.c common.c

CPPFLAGS += -Wno-unused-value -Wno-pointer-integer-compare -D_DEFAULT_SOURCE
LDADD=-lm

.include "../../mk/prog.mk"
