BINT=usr/bin
SUBDIR = env dirname basename id tee yes head printf wc \
	tty uniq nice grep sed nl seq base64 comm expand logname \
	printenv timeout sort join paste cut tail fmt \
	realpath split fold du mkfifo csplit stat mktemp nohup pr \
	xinstall tr xargs pathchk find uname asa apply banner \
	biff patch cal cmp touch mkstr sdiff renice deroff \
	col cksum locate users who write hexdump whereis vis unvis

.export BINT
.include <bsd.subdir.mk>
